// src/components/react/ButtonClassHide.tsx
import React, { useState } from 'react';

const HideClassButton = ({ name, classname }) => {
  const [isActive, setIsActive] = useState(false);

  const toggleCategory = () => {
    const elements = document.querySelectorAll(`.${classname}`);
    elements.forEach(element => {
      element.classList.toggle('hidden');
    });
    setIsActive(!isActive);
    hideLastVisibleLine();
  };

  const hideLastVisibleLine = () => {
    const elements = Array.from(document.querySelectorAll('.education__time'));
    const visibleElements = elements.filter((element: HTMLElement) => element.offsetParent !== null);
    // Add your code here to hide the line of the last visible element
  };

  return (
    <div className={`button_custom_container ${isActive ? 'toggled_active' : ''}`}>
      <button data-classname={classname} className="button_custom" onClick={toggleCategory}>
        {name}
      </button>
    </div>
  );
};

export default HideClassButton;

// src/components/vue/ButtonClassHide.vue
<template>

    <button @click="toggleCategory" :class="{'toggled_active': isActive }">
      <!-- Button content here -->
    </button>
  </template>

  <script lang="ts">
  export default {
    props: {
      classname: {
        type: String,
        required: true,
      },
      name: {
        type: String,
        required: true,
      },
      isActive: {
        type: Boolean,
        default: true,
      },
    },
    methods: {
      toggleCategory() {
        const elements = document.querySelectorAll(`.${this.classname}`);
        elements.forEach(element => {
          element.classList.toggle('hidden');
        });
        this.isActive = !this.isActive;
        this.hideLastVisibleLine();
      },
      hideLastVisibleLine() {
        const elements = Array.from(document.querySelectorAll('.education__time'));
        const visibleElements = elements.filter((element: HTMLElement) => element.offsetParent !== null);
        for (let i = 0; i < visibleElements.length; i++) {
          const currentElement = visibleElements[i];
          const nextElement = visibleElements[i + 1];
          if (!nextElement) {
            const line = currentElement.querySelector('.education__line');
            if (line) {
                (line as HTMLElement).style.display = 'none';
            }
          }
        }
      },
    },
  };
  </script>
  <style>
  button.button_custom {
      background-color: rgba(0, 0, 0, 0.05);
      box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);
      position:relative;
      border: none;
      padding: 0.75rem 2rem;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 1rem;
      cursor: pointer;
      border-top: 1px solid rgba(255, 255, 255, 0.05);
      border-bottom: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 2rem;
      z-index: 1;
      letter-spacing: 0.1rem;
      overflow: hidden;
      backdrop-filter: blur(1.1rem);
      transition: 0.5s;
  }
  button.button_custom:hover {
      letter-spacing: 0.1rem;
      background-color: rgba(0, 0, 0, 0.1);
  }
  button.button_custom::before{
      content: '';
      position:absolute;
      top: 0;
      left: 0;
      width: 50%;
      height: 100%;
      background: linear-gradient(to left, rgba(255, 255, 255, 0.15), transparent);
      transform: skewX(45deg) translateX(0);
      transition: 0.5s
  }
  button.button_custom:hover::before{
      transform: skewX(45deg) translateX(200%)
  }
  .button_custom_container{
      position:relative;
      overflow:hidden;
      width: 100%;
      height: 100%;
      border-radius: 2rem;
      transition: 0.5s
  }
  .button_custom_container::before{
      content: '';
      position:absolute;
      left: 50%;
      transform: translateX(-50%);
      bottom: -1.1rem;
      width: 30px;
      height: 10px;
      background: rgb(143, 0, 19);
      box-shadow:
          0 0 5px rgb(143, 0, 19),
          0 0 10px rgb(143, 0, 19),
          0 0 30px rgb(143, 0, 19),
          0 0 60px rgb(143, 0, 19);
      border-radius: 2rem;
      transition: 0.5s;
      transition-delay: 0.1s;
  }
  .button_custom_container.toggled_active::before{
      bottom: 0;
      width: 70%;
      height: 60%;
      background: rgb(0, 255, 0);
      box-shadow:
          0 0 5px rgb(0, 255, 0),
          0 0 10px rgb(0, 255, 0),
          0 0 30px rgb(0, 255, 0),
          0 0 60px rgb(0, 255, 0);
      border-radius: 00%;
      transition-delay: 0.1s;
  }
  .button_custom_container.toggled_active>button{
      color: white;
      transition-delay: 0.1s;
  }
  .button_custom_container>button{
      color: rgb(167, 167, 167);
      transition-delay: 0.1s;
  }

  .button_custom_container::after{
      content: '';
      position:absolute;
      left: 50%;
      transform: translateX(-50%);
      top: -1rem;
      width: 30px;
      height: 10px;
      background: rgb(143, 0, 19);
      box-shadow:
          0 0 5px rgb(143, 0, 19),
          0 0 10px rgb(143, 0, 19),
          0 0 30px rgb(143, 0, 19),
          0 0 60px rgb(143, 0, 19);
      border-radius: 2rem;
      transition: 0.5s;
      transition-delay: 0.1s;
  }
  .button_custom_container.toggled_active::after{
      top: 0;
      width: 50%;
      height: 50%;
      border-radius: 50%;
      transition-delay: 0.1s;
      background: rgb(0, 255, 0);
      box-shadow:
          0 0 5px rgb(0, 255, 0),
          0 0 10px rgb(0, 255, 0),
          0 0 30px rgb(0, 255, 0),
          0 0 60px rgb(0, 255, 0);
  }


  .toggled {
      background-color: #100418;
  }

  @keyframes slideaway {
    from { display: block; }
    to { transform: translateY(40px); opacity: 0;}
  }

  .hide {
    animation: slideaway 200ms;
    display: none;
  }
</style>
